//
//  PhrasesMock.swift
//  BlessedWords
//
//  Created by Juliano Sgarbossa on 24/07/25.
//

import Foundation

let phrases: [String] = [
    "Deus é amor. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "O justo viverá da fé. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "O Senhor é o meu pastor; nada me faltará. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "Não temas, porque eu sou contigo. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "Deus é amor. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "A paz de Deus guardará os vossos corações. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "O Senhor é o meu pastor; nada me faltará. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "Posso todas as coisas naquele que me fortalece. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "A bênção do Senhor é que enriquece. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O Senhor te abençoe e te guarde. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "A paz de Deus guardará os vossos corações. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "O Senhor é o meu pastor; nada me faltará. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "A bênção do Senhor é que enriquece. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "O justo viverá da fé. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "Deus é amor. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "Posso todas as coisas naquele que me fortalece. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "O justo viverá da fé. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O Senhor é o meu pastor; nada me faltará. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "Em tudo dai graças. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O Senhor te abençoe e te guarde. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "Deus é amor. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "Não temas, porque eu sou contigo. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "A bênção do Senhor é que enriquece. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "Em tudo dai graças. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "A bênção do Senhor é que enriquece. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O Senhor te abençoe e te guarde. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "Deus é amor. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "A paz de Deus guardará os vossos corações. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O Senhor te abençoe e te guarde. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "A bênção do Senhor é que enriquece. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "Em tudo dai graças. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "A bênção do Senhor é que enriquece. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "Não temas, porque eu sou contigo. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "Deus é amor. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "Não temas, porque eu sou contigo. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "O Senhor é o meu pastor; nada me faltará. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "Deus é amor. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "A paz de Deus guardará os vossos corações. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "Não temas, porque eu sou contigo. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O Senhor é o meu pastor; nada me faltará. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "Posso todas as coisas naquele que me fortalece. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "Em tudo dai graças. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "A bênção do Senhor é que enriquece. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "Deus é amor. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "A bênção do Senhor é que enriquece. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O Senhor te abençoe e te guarde. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O justo viverá da fé. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "A bênção do Senhor é que enriquece. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O Senhor é o meu pastor; nada me faltará. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "O justo viverá da fé. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O Senhor é o meu pastor; nada me faltará. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "Posso todas as coisas naquele que me fortalece. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "Posso todas as coisas naquele que me fortalece. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "A bênção do Senhor é que enriquece. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "O justo viverá da fé. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "Deus é amor. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "O Senhor é o meu pastor; nada me faltará. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "Não temas, porque eu sou contigo. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "Posso todas as coisas naquele que me fortalece. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O justo viverá da fé. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "Posso todas as coisas naquele que me fortalece. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "Deus é amor. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "Posso todas as coisas naquele que me fortalece. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "A paz de Deus guardará os vossos corações. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "Deus é amor. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "Deus é amor. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "Deus é amor. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "Em tudo dai graças. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O Senhor é o meu pastor; nada me faltará. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "Deus é amor. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "Em tudo dai graças. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "Em tudo dai graças. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "A bênção do Senhor é que enriquece. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "O justo viverá da fé. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O justo viverá da fé. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "O Senhor é o meu pastor; nada me faltará. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "Posso todas as coisas naquele que me fortalece. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "A paz de Deus guardará os vossos corações. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "A bênção do Senhor é que enriquece. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O Senhor te abençoe e te guarde. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "Não temas, porque eu sou contigo. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O justo viverá da fé. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "Posso todas as coisas naquele que me fortalece. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "A paz de Deus guardará os vossos corações. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "Deus é amor. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "A bênção do Senhor é que enriquece. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O justo viverá da fé. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "A bênção do Senhor é que enriquece. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O Senhor te abençoe e te guarde. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O Senhor é o meu pastor; nada me faltará. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "O Senhor te abençoe e te guarde. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O Senhor te abençoe e te guarde. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O Senhor te abençoe e te guarde. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "O Senhor é o meu pastor; nada me faltará. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "Não temas, porque eu sou contigo. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O Senhor te abençoe e te guarde. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "O justo viverá da fé. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O Senhor te abençoe e te guarde. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "Não temas, porque eu sou contigo. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O Senhor te abençoe e te guarde. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O Senhor te abençoe e te guarde. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O Senhor é o meu pastor; nada me faltará. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "Deus é amor. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "Em tudo dai graças. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "O Senhor é o meu pastor; nada me faltará. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "O Senhor é o meu pastor; nada me faltará. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "O Senhor é o meu pastor; nada me faltará. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "Em tudo dai graças. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O Senhor te abençoe e te guarde. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "Não temas, porque eu sou contigo. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "A paz de Deus guardará os vossos corações. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "Em tudo dai graças. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "Não temas, porque eu sou contigo. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "A paz de Deus guardará os vossos corações. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "Deus é amor. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "Em tudo dai graças. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "O justo viverá da fé. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O Senhor é o meu pastor; nada me faltará. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "A paz de Deus guardará os vossos corações. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "Em tudo dai graças. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "A paz de Deus guardará os vossos corações. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "A paz de Deus guardará os vossos corações. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "Deus é amor. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "O Senhor te abençoe e te guarde. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "Deus é amor. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "O Senhor te abençoe e te guarde. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "Em tudo dai graças. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "Em tudo dai graças. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "Deus é amor. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "A bênção do Senhor é que enriquece. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "Deus é amor. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "Deus é amor. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "O justo viverá da fé. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "Deus é amor. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "Deus é amor. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O justo viverá da fé. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "Posso todas as coisas naquele que me fortalece. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O Senhor te abençoe e te guarde. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O Senhor te abençoe e te guarde. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "Em tudo dai graças. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "A bênção do Senhor é que enriquece. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "Deus é amor. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "A paz de Deus guardará os vossos corações. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "A paz de Deus guardará os vossos corações. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "Posso todas as coisas naquele que me fortalece. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "Em tudo dai graças. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "Não temas, porque eu sou contigo. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "O Senhor é o meu pastor; nada me faltará. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "Em tudo dai graças. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "Posso todas as coisas naquele que me fortalece. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "O justo viverá da fé. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "Posso todas as coisas naquele que me fortalece. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "O Senhor é o meu pastor; nada me faltará. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "A bênção do Senhor é que enriquece. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "O Senhor é o meu pastor; nada me faltará. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "Posso todas as coisas naquele que me fortalece. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "O justo viverá da fé. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "Em tudo dai graças. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "O justo viverá da fé. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O Senhor é o meu pastor; nada me faltará. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "O Senhor te abençoe e te guarde. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "A paz de Deus guardará os vossos corações. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O Senhor é o meu pastor; nada me faltará. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "A bênção do Senhor é que enriquece. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "Posso todas as coisas naquele que me fortalece. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "O justo viverá da fé. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O Senhor é o meu pastor; nada me faltará. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "Posso todas as coisas naquele que me fortalece. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "Deus é amor. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "Posso todas as coisas naquele que me fortalece. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "O Senhor é o meu pastor; nada me faltará. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "O Senhor te abençoe e te guarde. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "O Senhor te abençoe e te guarde. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "A paz de Deus guardará os vossos corações. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O justo viverá da fé. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "Posso todas as coisas naquele que me fortalece. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "O Senhor é o meu pastor; nada me faltará. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "O Senhor te abençoe e te guarde. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "A paz de Deus guardará os vossos corações. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "A bênção do Senhor é que enriquece. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O justo viverá da fé. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "Em tudo dai graças. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "O Senhor te abençoe e te guarde. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "Deus é amor. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "O Senhor é o meu pastor; nada me faltará. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "Posso todas as coisas naquele que me fortalece. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "O Senhor te abençoe e te guarde. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "Em tudo dai graças. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "Em tudo dai graças. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "Deus é amor. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "A bênção do Senhor é que enriquece. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "O justo viverá da fé. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "O Senhor te abençoe e te guarde. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "Não temas, porque eu sou contigo. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "Em tudo dai graças. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O Senhor te abençoe e te guarde. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O justo viverá da fé. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "Não temas, porque eu sou contigo. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "Deus é amor. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "Em tudo dai graças. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "Deus é amor. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "A bênção do Senhor é que enriquece. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "Deus é amor. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "A bênção do Senhor é que enriquece. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O Senhor é o meu pastor; nada me faltará. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "Não temas, porque eu sou contigo. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "A paz de Deus guardará os vossos corações. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "Em tudo dai graças. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O Senhor te abençoe e te guarde. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "Em tudo dai graças. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "Posso todas as coisas naquele que me fortalece. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "A paz de Deus guardará os vossos corações. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "Deus é amor. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "O Senhor te abençoe e te guarde. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "O Senhor é o meu pastor; nada me faltará. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "Não temas, porque eu sou contigo. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "Posso todas as coisas naquele que me fortalece. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "Em tudo dai graças. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "O justo viverá da fé. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "Não temas, porque eu sou contigo. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "Deus é amor. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "Deus é amor. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "Não temas, porque eu sou contigo. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "A bênção do Senhor é que enriquece. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "A bênção do Senhor é que enriquece. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "Posso todas as coisas naquele que me fortalece. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "Em tudo dai graças. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O Senhor é o meu pastor; nada me faltará. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "Em tudo dai graças. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "Deus é amor. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "A bênção do Senhor é que enriquece. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "Posso todas as coisas naquele que me fortalece. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "Posso todas as coisas naquele que me fortalece. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O justo viverá da fé. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "Não temas, porque eu sou contigo. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "O justo viverá da fé. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "O justo viverá da fé. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "O Senhor te abençoe e te guarde. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "O Senhor é o meu pastor; nada me faltará. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "Não temas, porque eu sou contigo. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "O justo viverá da fé. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "Em tudo dai graças. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "Em tudo dai graças. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O justo viverá da fé. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O justo viverá da fé. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "A paz de Deus guardará os vossos corações. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "A bênção do Senhor é que enriquece. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "Posso todas as coisas naquele que me fortalece. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "O Senhor é o meu pastor; nada me faltará. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "Não temas, porque eu sou contigo. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "A paz de Deus guardará os vossos corações. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "A paz de Deus guardará os vossos corações. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "Deus é amor. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "Deus é amor. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "Posso todas as coisas naquele que me fortalece. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "A paz de Deus guardará os vossos corações. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "Não temas, porque eu sou contigo. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "Posso todas as coisas naquele que me fortalece. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "Posso todas as coisas naquele que me fortalece. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O justo viverá da fé. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "A paz de Deus guardará os vossos corações. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "O Senhor te abençoe e te guarde. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "O justo viverá da fé. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "O Senhor te abençoe e te guarde. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "Em tudo dai graças. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "O justo viverá da fé. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "Posso todas as coisas naquele que me fortalece. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "A paz de Deus guardará os vossos corações. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "Deus é amor. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "Em tudo dai graças. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "Não temas, porque eu sou contigo. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "O Senhor te abençoe e te guarde. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "Não temas, porque eu sou contigo. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "Não temas, porque eu sou contigo. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "O justo viverá da fé. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "A bênção do Senhor é que enriquece. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "Em tudo dai graças. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O Senhor te abençoe e te guarde. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "A paz de Deus guardará os vossos corações. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "Não temas, porque eu sou contigo. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "O Senhor te abençoe e te guarde. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "Em tudo dai graças. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "O Senhor te abençoe e te guarde. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "Em tudo dai graças. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "Posso todas as coisas naquele que me fortalece. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "Posso todas as coisas naquele que me fortalece. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "O Senhor é o meu pastor; nada me faltará. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "A bênção do Senhor é que enriquece. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "O Senhor é o meu pastor; nada me faltará. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "Não temas, porque eu sou contigo. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "Deus é amor. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "Deus é amor. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "A paz de Deus guardará os vossos corações. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O justo viverá da fé. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "A paz de Deus guardará os vossos corações. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "Em tudo dai graças. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "O Senhor te abençoe e te guarde. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "Em tudo dai graças. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O Senhor é o meu pastor; nada me faltará. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "A bênção do Senhor é que enriquece. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "A paz de Deus guardará os vossos corações. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "A paz de Deus guardará os vossos corações. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O Senhor é o meu pastor; nada me faltará. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "A paz de Deus guardará os vossos corações. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "A bênção do Senhor é que enriquece. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "O justo viverá da fé. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O Senhor te abençoe e te guarde. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "Deus é amor. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "Não temas, porque eu sou contigo. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "O Senhor te abençoe e te guarde. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Isso nos ensina a depender do Senhor em todas as áreas da vida e não duvidar de Seu amor.",
    "O Senhor te abençoe e te guarde. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "A paz de Deus guardará os vossos corações. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "Deus é amor. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "O Senhor te abençoe e te guarde. Confie nisso, mesmo quando tudo parecer escuro — a luz virá, pois Deus cuida de cada detalhe.",
    "A bênção do Senhor é que enriquece. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "Posso todas as coisas naquele que me fortalece. Reflita sobre isso e leve a certeza de que Deus está agindo mesmo no silêncio.",
    "O justo viverá da fé. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "Posso todas as coisas naquele que me fortalece. Que essa verdade guie seu coração hoje, trazendo esperança mesmo nos dias difíceis.",
    "Deus é amor. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante.",
    "Em tudo dai graças. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "O choro pode durar uma noite, mas a alegria vem pela manhã. Uma promessa que se cumpre quando colocamos nossa confiança naquele que nunca falha.",
    "Deus é amor. Lembre-se que Ele está no controle e nenhum problema é maior que Sua presença constante."
]
